# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import biblioteca_pb2 as biblioteca__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in biblioteca_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BibliotecaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CadastrarUsuario = channel.unary_unary(
                '/biblioteca.BibliotecaService/CadastrarUsuario',
                request_serializer=biblioteca__pb2.CadastrarUsuarioRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.CadastrarGenero = channel.unary_unary(
                '/biblioteca.BibliotecaService/CadastrarGenero',
                request_serializer=biblioteca__pb2.CadastrarGeneroRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.GeneroResponse.FromString,
                _registered_method=True)
        self.CadastrarLivro = channel.unary_unary(
                '/biblioteca.BibliotecaService/CadastrarLivro',
                request_serializer=biblioteca__pb2.CadastrarLivroRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.LivroResponse.FromString,
                _registered_method=True)
        self.ListarUsuarios = channel.unary_unary(
                '/biblioteca.BibliotecaService/ListarUsuarios',
                request_serializer=biblioteca__pb2.Empty.SerializeToString,
                response_deserializer=biblioteca__pb2.ListaUsuariosResponse.FromString,
                _registered_method=True)
        self.ListarLivros = channel.unary_unary(
                '/biblioteca.BibliotecaService/ListarLivros',
                request_serializer=biblioteca__pb2.Empty.SerializeToString,
                response_deserializer=biblioteca__pb2.ListaLivrosResponse.FromString,
                _registered_method=True)
        self.ListarEmprestimosAtivos = channel.unary_unary(
                '/biblioteca.BibliotecaService/ListarEmprestimosAtivos',
                request_serializer=biblioteca__pb2.Empty.SerializeToString,
                response_deserializer=biblioteca__pb2.ListaEmprestimosResponse.FromString,
                _registered_method=True)
        self.ListarMultas = channel.unary_unary(
                '/biblioteca.BibliotecaService/ListarMultas',
                request_serializer=biblioteca__pb2.Empty.SerializeToString,
                response_deserializer=biblioteca__pb2.ListaMultasResponse.FromString,
                _registered_method=True)
        self.ConsultarLivro = channel.unary_unary(
                '/biblioteca.BibliotecaService/ConsultarLivro',
                request_serializer=biblioteca__pb2.ConsultarLivroRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.LivroResponse.FromString,
                _registered_method=True)
        self.ConsultarMultaUsuario = channel.unary_unary(
                '/biblioteca.BibliotecaService/ConsultarMultaUsuario',
                request_serializer=biblioteca__pb2.ConsultarMultaUsuarioRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.MultaUsuarioResponse.FromString,
                _registered_method=True)
        self.RealizarEmprestimo = channel.unary_unary(
                '/biblioteca.BibliotecaService/RealizarEmprestimo',
                request_serializer=biblioteca__pb2.EmprestimoRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.OperacaoResponse.FromString,
                _registered_method=True)
        self.DevolverLivro = channel.unary_unary(
                '/biblioteca.BibliotecaService/DevolverLivro',
                request_serializer=biblioteca__pb2.DevolucaoRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.DevolucaoResponse.FromString,
                _registered_method=True)
        self.QuitarMulta = channel.unary_unary(
                '/biblioteca.BibliotecaService/QuitarMulta',
                request_serializer=biblioteca__pb2.QuitarMultaRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.OperacaoResponse.FromString,
                _registered_method=True)


class BibliotecaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CadastrarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CadastrarGenero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CadastrarLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarLivros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarEmprestimosAtivos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMultas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarMultaUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RealizarEmprestimo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DevolverLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuitarMulta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibliotecaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CadastrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastrarUsuario,
                    request_deserializer=biblioteca__pb2.CadastrarUsuarioRequest.FromString,
                    response_serializer=biblioteca__pb2.UsuarioResponse.SerializeToString,
            ),
            'CadastrarGenero': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastrarGenero,
                    request_deserializer=biblioteca__pb2.CadastrarGeneroRequest.FromString,
                    response_serializer=biblioteca__pb2.GeneroResponse.SerializeToString,
            ),
            'CadastrarLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastrarLivro,
                    request_deserializer=biblioteca__pb2.CadastrarLivroRequest.FromString,
                    response_serializer=biblioteca__pb2.LivroResponse.SerializeToString,
            ),
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=biblioteca__pb2.Empty.FromString,
                    response_serializer=biblioteca__pb2.ListaUsuariosResponse.SerializeToString,
            ),
            'ListarLivros': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarLivros,
                    request_deserializer=biblioteca__pb2.Empty.FromString,
                    response_serializer=biblioteca__pb2.ListaLivrosResponse.SerializeToString,
            ),
            'ListarEmprestimosAtivos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarEmprestimosAtivos,
                    request_deserializer=biblioteca__pb2.Empty.FromString,
                    response_serializer=biblioteca__pb2.ListaEmprestimosResponse.SerializeToString,
            ),
            'ListarMultas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMultas,
                    request_deserializer=biblioteca__pb2.Empty.FromString,
                    response_serializer=biblioteca__pb2.ListaMultasResponse.SerializeToString,
            ),
            'ConsultarLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarLivro,
                    request_deserializer=biblioteca__pb2.ConsultarLivroRequest.FromString,
                    response_serializer=biblioteca__pb2.LivroResponse.SerializeToString,
            ),
            'ConsultarMultaUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarMultaUsuario,
                    request_deserializer=biblioteca__pb2.ConsultarMultaUsuarioRequest.FromString,
                    response_serializer=biblioteca__pb2.MultaUsuarioResponse.SerializeToString,
            ),
            'RealizarEmprestimo': grpc.unary_unary_rpc_method_handler(
                    servicer.RealizarEmprestimo,
                    request_deserializer=biblioteca__pb2.EmprestimoRequest.FromString,
                    response_serializer=biblioteca__pb2.OperacaoResponse.SerializeToString,
            ),
            'DevolverLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.DevolverLivro,
                    request_deserializer=biblioteca__pb2.DevolucaoRequest.FromString,
                    response_serializer=biblioteca__pb2.DevolucaoResponse.SerializeToString,
            ),
            'QuitarMulta': grpc.unary_unary_rpc_method_handler(
                    servicer.QuitarMulta,
                    request_deserializer=biblioteca__pb2.QuitarMultaRequest.FromString,
                    response_serializer=biblioteca__pb2.OperacaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biblioteca.BibliotecaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biblioteca.BibliotecaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BibliotecaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CadastrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/CadastrarUsuario',
            biblioteca__pb2.CadastrarUsuarioRequest.SerializeToString,
            biblioteca__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CadastrarGenero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/CadastrarGenero',
            biblioteca__pb2.CadastrarGeneroRequest.SerializeToString,
            biblioteca__pb2.GeneroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CadastrarLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/CadastrarLivro',
            biblioteca__pb2.CadastrarLivroRequest.SerializeToString,
            biblioteca__pb2.LivroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/ListarUsuarios',
            biblioteca__pb2.Empty.SerializeToString,
            biblioteca__pb2.ListaUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarLivros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/ListarLivros',
            biblioteca__pb2.Empty.SerializeToString,
            biblioteca__pb2.ListaLivrosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarEmprestimosAtivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/ListarEmprestimosAtivos',
            biblioteca__pb2.Empty.SerializeToString,
            biblioteca__pb2.ListaEmprestimosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMultas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/ListarMultas',
            biblioteca__pb2.Empty.SerializeToString,
            biblioteca__pb2.ListaMultasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/ConsultarLivro',
            biblioteca__pb2.ConsultarLivroRequest.SerializeToString,
            biblioteca__pb2.LivroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarMultaUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/ConsultarMultaUsuario',
            biblioteca__pb2.ConsultarMultaUsuarioRequest.SerializeToString,
            biblioteca__pb2.MultaUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RealizarEmprestimo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/RealizarEmprestimo',
            biblioteca__pb2.EmprestimoRequest.SerializeToString,
            biblioteca__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DevolverLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/DevolverLivro',
            biblioteca__pb2.DevolucaoRequest.SerializeToString,
            biblioteca__pb2.DevolucaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuitarMulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/QuitarMulta',
            biblioteca__pb2.QuitarMultaRequest.SerializeToString,
            biblioteca__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
